### ISSUE TITLE
Get-Gist returns 30 gists 

### ISSUE THREAD

**Issue by majkinetor** [dotps1/PSGist#2]
and its rather slow in that.

Comparing to that, [gist gem](https://github.com/defunkt/gist) returns all after few seconds.

**Comment by dotps1** [comment]
one reason why it is slower, is when you get multi gists without specifying the -Id, it truncates the Commit History, as well as the File content, so, in the Gist class, when its constructing the object, if the FileContent is null, it actually sends another request to get that data.

I would recommend using the -Id parameter to retrieve a single Gist.  Or Use the Find-Gist option to help filter your results.

**Comment by majkinetor** [comment]
That is unappropriate then, IMO. `Get-xxx` functions should return everything by default. Also, its not practical to use Id in general case. Typical scenario is to get all gists and filter them using regular powershell syntax which is way more powerful then any API supported filtering. 

It is also intuitive that `Gists:` provider would list all gists. Some people and some tools also use tags in the description (see gistlist for example) which could be created as folders.

**Comment by dotps1** [comment]
that is what I am saying as to why its slower, because it is getting everything.  but when no ID is used, it has to make 2 calls to GitHub to get the data, not just one.

Anyway, this is an Open Source project, so feel free to fork it and do what ever you see fit In Your Opinion.

**Comment by majkinetor** [comment]
> Anyway, this is an Open Source project, so feel free to fork it and do what ever you see fit In Your Opinion.

Epic attitutde.

**Comment by dotps1** [comment]
yes, maybe that wasn't worded the best, but really, this is a project I have developed for my use, I only share so _if_ you'd like to use it, go for it.  But to just open an issue to tell me I'm doing wrong In Your Opinion probably is going to get any action.  If you'd like to at least open a PR and contribute to this project, that would be accepted.

**Comment by dotps1** [comment]
so, after revisiting this when I had some time to look into it more in depth there are quite a few differences here between PSGist and the gist gem.
1. I don't know hardly anything about ruby, but it looks to me as though that gem only returns a concated string of the url and description, if there is one.  PSGist is building entrie .net objects in the backend, so yes, its slower as its not just returning and Array of strings.
2.  its barely slower, here are the measure commands differences:

```
GitHub:\ PS> Measure-Command -Expression { gist -l dotps1 }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 268
Ticks             : 22684210
TotalDays         : 2.62548726851852E-05
TotalHours        : 0.000630116944444444
TotalMinutes      : 0.0378070166666667
TotalSeconds      : 2.268421
TotalMilliseconds : 2268.421



GitHub:\ PS> ipmo .\psgist\PSGist
GitHub:\ PS> Measure-Command -Expression { Get-Gist }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 346
Ticks             : 33462616
TotalDays         : 3.87298796296296E-05
TotalHours        : 0.000929517111111111
TotalMinutes      : 0.0557710266666667
TotalSeconds      : 3.3462616
TotalMilliseconds : 3346.2616
```

its a second slower, a second.  But with that second you have everything from the Gist object you can now do what ever with, namely the Files and there content.

``` powershell
Class Gist {
    [Int]$Comments
    [Uri]$CommentsUrl
    [Uri]$CommitsUrl
    [DateTime]$CreatedAt
    [string]$Description
    [GistFile[]]$Files
    [GistFork[]]$Forks
    [Uri]$ForksUrl
    [GistHistory[]]$History
    [Uri]$HtmlUrl
    [String]$Id
    [GistUser]$Owner
    [Bool]$Public
    [Uri]$PullUrl
    [Uri]$PushUrl
    [Bool]$Truncated
    [DateTime]$UpdatedAt
    [Uri]$Url

    # This contructor works passing a gist response from the API directly into it.
    Gist([Object]$object) {
        $this.CommentsUrl = $object.comments_url
        $this.Comments = $object.comments
        $this.CommitsUrl = $object.commits_url
        $this.CreatedAt = $object.created_at
        $this.Description = $object.Description
        $this.Files = $object.files.PSObject.Properties.Value
        $this.Forks = $object.forks
        $this.ForksUrl = $object.forks_url
        $this.History = $object.history
        $this.HtmlUrl = $object.html_url
        $this.Id = $object.id
        $this.Owner = $object.owner
        $this.Public =$object.public
        $this.PullUrl = $object.git_pull_url
        $this.PushUrl = $object.git_push_url
        $this.Truncated = $object.truncated
        $this.UpdatedAt = $object.updated_at
        $this.Url = $object.url
    }

    # Constructor for manually defining properties.
    # these are the properties that are settable when creating a new Gist via the API.
    Gist([String]$Description, [GistFile[]]$Files, [Bool]$Public) {
        $this.Description = $Description
        $this.Files = $Files
        $this.Public = $Public
    }

    # TODO: Create() and Delete() methods.
}
```

  and that 1 second is while it creates 25 Gist objects:

```
GitHub:\ PS> (Get-Gist).Count
25
```

Also, another difference (not in these times because I did not create an OAuth token for the gist gem) is that I do not keep your Gist OAuth token in memory as an env variable.  It serialized to disk, so every time you make a call, that token needs to be deserialized.  Probably not a huge cost, but it is there.  

Now as far as getting _all_ gists, that can be done if I allow you to authenticate anonymously, which I may consider, at least for the Get-Gist cmdlet anyway.  But in the mean time, if that one second is that crucial, and you only need the git.io shortened URL and the description, then I suggest you use the gist gem.
